# Generated by Django 2.0.4 on 2018-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.CharField(max_length=100, null=True, verbose_name='Фото')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
            ],
        ),
    ]
