# Generated by Django 2.0.4 on 2018-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alize', '0002_auto_20180416_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
