# Generated by Django 2.0.4 on 2018-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alize', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='team',
            field=models.CharField(max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
