# Generated by Django 2.0.4 on 2018-04-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alize', '0006_about_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='team',
        ),
    ]
