# Generated by Django 2.0.4 on 2018-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alize', '0007_remove_about_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.CharField(max_length=100, null=True, verbose_name='Фото')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alize.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Steak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.CharField(max_length=100, null=True, verbose_name='Фото')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alize.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
