# Generated by Django 2.0.4 on 2018-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alize', '0011_auto_20180422_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added: '),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Write your Comment'),
        ),
    ]
